name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run unittests
        run: python -m unittest discover -p 'tests.py'
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy .
